### ISSUE TITLE
Add option for randomizing sleeping buffs/debuffs

### ISSUE THREAD

**Issue by Freddo3000** [Nuytemans-Dieter/BetterSleeping#176]
**Describe the new feature you have in mind**
Simply being able to randomize how many levels a buff will have, how long it will last and an overall chance of gaining the buff/debuff.

Example:
```yml
sleeper_buffs:
  speed:
    time: 20-60 # Lasts between 20-60 seconds.
    level: 1-3 # levels between 1 and 3
    odds: 0.2 # 20% chance of gaining the buff in the first place
```
