### ISSUE TITLE
BS4 - Players are kicked out of the bed | delay between enough sleepers & nighttime fastforward

### ISSUE THREAD

**Issue by NitroxydeX** [Nuytemans-Dieter/BetterSleeping#258]
## Potential bug
After updating from version 3 to 4 there is some kind of strange (intentional) behavior.
The release notes stated:
> Leaving the bed no longer subtracts a sleeper, it is now good enough to enter your bed and go about your business right away. This allows players to have more time to enjoy playing on the server.

It sounded like this is an **_option_** for the user to actively _**choose**_ to leave the bed if he wants to. Instead it seems to be a default that players are getting kicked out of their bed when counted against the minimum required sleepers. It would be nice if this could be controlled via a config setting.

With this behavior it seems like the plugin now waits for a specific amount of time after it detected that enough players entered their bed before the night time is fast forwarded. Is this intentional? If yes it would be nice to have an option for this as well.

**Comment by Nuytemans-Dieter** [comment]
Thank you for reporting an issue!

It should indeed be optional for players to leave their bed (they should **not** be kicked out by BetterSleeping until morning).
One possible cause is if all players in a world are sleeping because Minecraft itself kicks everybody out of bed in that case.

Time acceleration should occur as soon as a sufficient amount of players are sleeping so it seems like something is off indeed.
If you want to, feel free to share your config (here or in a private ticket on our Discord) and I'll see if something in there may cause these issues.

This will be investigated and hopefully fixed by next release. Thanks!

**Comment by NitroxydeX** [comment]
Indeed this happens when everyone is sleeping. The only occurrence to this in v3 was if there was only 1 player in that world so the night got skipped instant instead of the specified value for smooth night transition.

Regarding the delay: It seems like the plugin is waiting for a specific tick time instead of the tick time the player can actually sleep (10:27 minutes). After this time point it is always instant

<details>
<summary>config.yml</summary>
<p>

```yml
#
# ____       _   _            ____  _                    _                       _  _
#| __ )  ___| |_| |_ ___ _ __/ ___|| |    ___  ___ _ __ (_)_ __   __ _    __   _| || |
#|  _ \ / _ \ __| __/ _ \ '__\___ \| |   / _ \/ _ \ '_ \| | '_ \ / _` |   \ \ / / || |_
#| |_) |  __/ |_| ||  __/ |   ___) | |__|  __/  __/ |_) | | | | | (_| |    \ V /|__   _|
#|____/ \___|\__|\__\___|_|  |____/|_____\___|\___| .__/|_|_| |_|\__, |     \_/    |_|
#                                                 |_|            |___/



# To reset a BetterSleeping config file, you can simply delete it and perform /bs reload or restart the server

# Useful links:
# Our Spigot plugin page:                                       https://www.spigotmc.org/resources/bettersleeping-1-12-1-14.60837/
# For support or suggestions, head over to our Discord server:  https://discord.gg/AS46VGT
# You can find a live list of upcoming features/bug fixes here: https://github.com/Nuytemans-Dieter/BetterSleeping/issues
# The progress of the next release can be found here:           https://github.com/Nuytemans-Dieter/BetterSleeping/milestones
# Considered buying the premium version? (Spigot account needed)https://www.spigotmc.org/resources/bettersleeping-premium-1-13-1-16.78951/

# Configuration guide and default values:       https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources/config.yml
# All default config files can be found here:   https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources

# After changing this option, please delete 'lang.yml' and do /bs reload or restart your server
# The default language file to be used
# Options: en-US (English), nl-BE (Dutch), es-ES (Spanish), pt-PT (Portuguese), de-DE.yml (German), fr-FR (French), Chinese (zh-ZH)
# Want to disable all messages? Set this to: "silent". It will load an empty config files and will disable most messages
# Up-to-date list here: https://github.com/Nuytemans-Dieter/BetterSleeping/tree/v3.0.0/src/main/resources/lang
language: "de-DE"

# Choose where messages show up
# Messages are shown in the chat when set to false, and shown in the action bar when set to true
# This will ONLY work if you are using Spigot
action_bar_messages: true

# Use the bossbar to display the amount of sleeping players
enable_bossbar: true

# This is ran once on startup when enabled to fetch the latest version
update_notifier: true

# Whether or not phantoms should be disabled
disable_phantoms: false

# Whether you want to show particle animations when players are sleeping
# These are precomputed to save on processing time
enable_animations: true

# Whether you want to save BetterSleeping output to log files
save_logs: false

```
</details>  

<details>
<summary>sleeping_settings.yml</summary>

```yml
#
# ____       _   _            ____  _                    _                       _  _
#| __ )  ___| |_| |_ ___ _ __/ ___|| |    ___  ___ _ __ (_)_ __   __ _    __   _| || |
#|  _ \ / _ \ __| __/ _ \ '__\___ \| |   / _ \/ _ \ '_ \| | '_ \ / _` |   \ \ / / || |_
#| |_) |  __/ |_| ||  __/ |   ___) | |__|  __/  __/ |_) | | | | | (_| |    \ V /|__   _|
#|____/ \___|\__|\__\___|_|  |____/|_____\___|\___| .__/|_|_| |_|\__, |     \_/    |_|
#                                                 |_|            |___/


# To reset a BetterSleeping config file, you can simply delete it and perform /bs reload or restart the server

# Configuration guide and default values:       https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources/sleeping_settings.yml
# All default config files can be found here:   https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources

# Choose an option from below (percentage or absolute)
# With percentage, a relative amount of players needs to sleep (eg. needed: 30 -> 13 online players, 30% of 13 is 3,9. Will be rounded to the nearest number -> 4 sleeping players needed)
# With absolute, a static amount of players needs to sleep (eg. needed: 2 -> any amount of online players, 2 players need to sleep)
sleeper_calculator: "percentage"

# This depends on your sleeper_calculator setting
#     Percentage: This value is the percentage of players in a world that must sleep ([0, 100])
#     Absolute: This value is always the amount of players that must sleep, does not scale with the amount of online players!
needed: 50

# The duration (in seconds) of the night when enough players are sleeping
# Set this to 0 to skip the night instantly
# A normal night lasts 500 seconds
night_skip_length: 10

# The normal length of the day and night when not skipping (in seconds)
# This allows you to speed up or slow down the time
# Default: 700
day_length: 700
# Default: 500
night_length: 500


# The time in seconds that players need to wait before they can enter the bed again after leaving it
bed_enter_cooldown: 10

# Disable BetterSleeping in certain worlds. This option is case sensitive!
# Sleeping is always enabled in worlds that are not in this list
world_settings:
  worldname:
    enabled: true
    night_length: 500
    day_length: 700
    night_skip_length: 10
```

</details>  

<details>
<summary>buffs.yml</summary>

```yml
#
# ____       _   _            ____  _                    _                       _  _
#| __ )  ___| |_| |_ ___ _ __/ ___|| |    ___  ___ _ __ (_)_ __   __ _    __   _| || |
#|  _ \ / _ \ __| __/ _ \ '__\___ \| |   / _ \/ _ \ '_ \| | '_ \ / _` |   \ \ / / || |_
#| |_) |  __/ |_| ||  __/ |   ___) | |__|  __/  __/ |_) | | | | | (_| |    \ V /|__   _|
#|____/ \___|\__|\__\___|_|  |____/|_____\___|\___| .__/|_|_| |_|\__, |     \_/    |_|
#                                                 |_|            |___/


# To reset a BetterSleeping config file, you can simply delete it and perform /bs reload or restart the server

# Configuration guide and default values:       https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources/buffs.yml
# All default config files can be found here:   https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources

# These are effects that will be applied after sleeping, only on the players that have slept
# The idea is to give a well rested bonus so sleeping is encouraged and more people will try to sleep


# CONFIGURATION GUIDE:

# Not working? Try copy/pasting the contents of this file into http://www.yamllint.com/ to check for errors
# To disable an effect, simply remove it from the list

# For a list of possible buffs, check: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
# regeneration, absorption, jump, speed, damage_resistance, fast_digging, increase_damage, saturation

# time: The time in seconds for which the effect will be applied
# level: The level of the effect (may be an OP level but >90 may work in unintended ways)

# The commands in the list below are executed in the console for EACH (non-)sleeper
# One tag is supported at this time: <user>, which will be replaced by each user's name
# Uncomment the blocks below to enable them, you can add your own commands too!

#sleeper_commands:
#  - money give <user> 5

#non_sleeper_commands:
#  - say <user> did not sleep, pfuhhh!

# Sleeper_buffs are given for every sleeping player
# Non_sleepers_debuffs are given for every non-sleeping player
sleeper_buffs:
  regeneration:
    level: 1
    time: 10
  speed:
    level: 1
    time: 30
non_sleeper_debuffs:
  hunger:
    level: 1
    time: 10
  slow:
    time: 5
    level: 1
```

</details>  

bypassing.yml and hooks.yml aren't used and are on their default values generated by the plugin itself.
